---
- hosts: all_hosts
  become: true
  tasks:
          - name: deploy war file to tomcat from jenkins workspace
            action: src=/var/lib/jenkins/workspace/first/target/dynamic_new-${BUILD_NUMBER}.war dest=//home/ec2-user/jenkins.sh/apache-tomcat-8.5.49/webapps
