---
- hosts: all_hosts
  become: true
  tasks:
          - name: Downloading artifact
            action: get_url url=http://ec2-18-224-155-110.us-east-2.compute.amazonaws
.com:8081/nexus/service/local/repositories/devopstraining/content/phoenixTeam/WebAppl
ication-1.war dest=/home/ec2-user/apache-tomcat-9.0.27/webapps
